php-version = "8.2"

[source]
paths = ["municipio-theme-extensions.php", "source", "tests"]

[formatter]
print-width = 120

[linter]
integrations = ["phpunit"]

[linter.rules]
literal-named-argument = { enabled = false }
no-global = { level = "warning" }
cyclomatic-complexity = { level = "warning" }
